version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: replit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: replit_db
      POSTGRES_USER: replit_user
      POSTGRES_PASSWORD: replit_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - replit-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: replit-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://replit_user:replit_password@postgres:5432/replit_db
      NODE_ENV: development
    depends_on:
      - postgres
    networks:
      - replit-network

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   container_name: replit-web
  #   restart: unless-stopped
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     VITE_API_URL: http://localhost:3000
  #   depends_on:
  #     - api
  #   networks:
  #     - replit-network

volumes:
  postgres_data:

networks:
  replit-network:
    driver: bridge